# Stage 1
FROM node:14 as build-stage

WORKDIR /app
COPY package.json .
RUN npm install
RUN npm install -g @quasar/cli && \
    npm install -g @vue/cli && \
    npm install -g @vue/cli-init 
COPY . .


RUN npm run build

# Stage 2
FROM nginx:1.17.0-alpine

COPY --from=build-stage /app/dist/spa /usr/share/nginx/html
EXPOSE 8080

CMD nginx -g 'daemon off;'