// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt({
  rules: {
    radix: 'off',
    'no-void': 'off',
    'no-undef': 'off',
    'no-shadow': 'off',
    'no-unused-vars': 'off',
    'no-param-reassign': 'off',
    '@typescript-eslint/no-explicit-any': 'warn',
    'no-console': 'warn',
    'no-nested-ternary': 'off',
    'vue/html-self-closing': 'off',
    'no-underscore-dangle': 'off',
    '@typescript-eslint/no-shadow': 'error',
    '@typescript-eslint/no-var-requires': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    'max-classes-per-file': 'off',
    'vue/multi-word-component-names': 'off',
    'import/first': 'off',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/default': 'error',
    'import/export': 'error',
    'import/extensions': 'off',
    'import/no-unresolved': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/prefer-default-export': 'off',
    'prefer-destructuring': ['error', { object: true, array: false }],
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
  },
  ignores: [
    '/node_modules',
    '/.output',
    '/.nuxt',
    '.eslintrc.js',
    '/src-ssr',
    // Ignore files for PNPM, NPM and YARN
    'pnpm-lock.yaml',
    'package-lock.json',
    'yarn.lock',
  ],
});
