server:
  log_level: debug
  sentry:
    enabled: false
    dsn: https://d383400104b243a489c54831d4947f00@o1383368.ingest.sentry.io/6699794
  port: 8081
  postgres:
    host: localhost
    name: postgres
    user: postgres
    password: postgres
  redis:
    username:
    password:
    host: localhost
    port: 6379
    expiration_timeout: 259200
  hash_secret: oi.renimdeal
  imap:
    authentication_timeout: 10000
    connection_timeout: 90000
google_api:
  host: imap.gmail.com
  client:
    id: 865693030337-d1lmavgk1fp3nfk8dfo38j75nobn2vvl.apps.googleusercontent.com
    secret: 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
email_types:
  noreply: "accusereception,alerts,alert,auto-confirm,donotreply,do-notreply,do-not-reply,FeedbackForm,mail daemon,maildaemon,mailer daemon,mailer-daemon,mailermasters,ne_pas_repondre,nepasrepondre,ne-pas-repondre,no.reply,no_reply,noreply,no-reply,notification,notifications,notifications-noreply,notify,pasdereponse,password,reply-,send-as-noreply,support,systemalert,unsubscribe,wordpress"
  newsletter: "list-unsubscribe,list-id,list"
  transactional: "feedback-id,x-feedback-id,x-mandrill-user,x-mailer: mailchimp *,X-LinkedIn-*,x-mailer: ec-messenger*,x-mailer: nlserver *,x-marketoid,x-campaignid,x-Mailgun*,x-job"
test:
  imap_email: "honeypot@flyweight.tech"
  imap_host: "mail.gandi.net"
  imap_password: "9Jkxd54DutETkx"
