server:
  log_level: debug
  allowed_origins: 'http://localhost:8082'
  sentry:
    enabled: false
    dsn: https://sentry.io
  port: 8081
  supabase:
    url: 'http://localhost:54321'
    # The anon_key generated after you start your local supabase services
    token:
  redis:
    host: localhost
    port: 6379
    expiration_timeout: 259200 # expiration timeout for redis entries
  hash_secret: dev-hash # hash secret used to hash the users emails addresses
  imap:
    authentication_timeout: 10000
    connection_timeout: 90000
google_api:
  host: imap.gmail.com
  client: # to create you own client go to : https://developers.google.com/identity/protocols/oauth2
    id:
    secret:
email_types: # filtering headers and strings for emails addresses
  noreply: 'accusereception,alerts,alert,auto-confirm,donotreply,do-notreply,do-not-reply,FeedbackForm,mail daemon,maildaemon,mailer daemon,mailer-daemon,mailermasters,ne_pas_repondre,nepasrepondre,ne-pas-repondre,no.reply,no_reply,noreply,no-reply,notification,notifications,notifications-noreply,notify,pasdereponse,password,reply-,send-as-noreply,support,systemalert,unsubscribe,wordpress'
  newsletter: 'list-unsubscribe,list-id,list'
  transactional: 'feedback-id,x-feedback-id,x-mandrill-user,x-mailer: mailchimp *,X-LinkedIn-*,x-mailer: ec-messenger*,x-mailer: nlserver *,x-marketoid,x-campaignid,x-Mailgun*,x-job'
  list: 'list-post'
test: # used in tests
  imap_email: 'email@example.net'
  imap_host: 'mail.example.net'
  imap_password: 'devpassword'
