server:
  log_level: debug
  port: 8081
  postgres:
    name: postgres
    user: postgres
    password:
  redis:
    #username: redis
    #password: redispassword
    port: 6375
    expiration_timeout: 259200
  hash_secret: customsecret
  imap:
    authentication_timeout: 10000
    connection_timeout: 90000
google_api:
  host: imap.gmail.com
  client:
    id: 86*********337-d1********2vvl.apps.googleusercontent.com
    secret: GO*******************hXqV93
email_types:
  newsletter: "list-unsubscribe,list-id,list"
  transactional: "feedback-id,x-feedback-id,x-mandrill-user,x-mailer: ec-messenger*,x-mailer: nlserver *,x-marketoid,x-campaignid,x-Mailgun*"
test:
  imap_email: "leadminer@leadminer.io"
  imap_host: "imaphost"
  imap_password: "yourownpassword"
