server:
  log_level: debug
  allowed_origins: 'https://app.example.io'
  sentry: # To create your own, go to : https://sentry.io
    enabled:
    dsn:
  port: 8081
  supabase:
    connection_type: 'native' # 'native' or 'pgrest'
    connection_string: 'postgresql://postgres:postgres@localhost:54322/postgres'
    url:
    token:
  redis:
    username: # Optional
    password: # Optional
    tls: 'false'
    host:
    port: 6379
    expiration_timeout: 259200 # expiration timeout for redis entries
  hash_secret: super_secret_hash_secret # hash secret used to hash the users emails addresses
  imap:
    fetch_body: 'false'
    authentication_timeout: 10000
    connection_timeout: 90000
google_api:
  host:
  client: # To create you own client go to : https://developers.google.com/identity/protocols/oauth2
    id:
    secret:
email_types: # filtering headers and strings for emails addresses
  noreply: 'accusereception,alerts,alert,auto-confirm,donotreply,do-notreply,do-not-reply,FeedbackForm,mail daemon,maildaemon,mailer daemon,mailer-daemon,mailermasters,ne_pas_repondre,nepasrepondre,ne-pas-repondre,no.reply,no_reply,noreply,no-reply,notification,notifications,notifications-noreply,notify,pasdereponse,password,reply-,send-as-noreply,support,systemalert,unsubscribe,wordpress'
  newsletter: 'list-unsubscribe,list-id,list'
  transactional: 'feedback-id,x-feedback-id,x-mandrill-user,x-mailer: mailchimp *,X-LinkedIn-*,x-mailer: ec-messenger*,x-mailer: nlserver *,x-marketoid,x-campaignid,x-Mailgun*,x-job'
  list: 'list-post'

test:
  imap_email: 'test@example.io'
  imap_host: 'mail.example.com'
  imap_password: 'password'
