version = 1

#[[analyzers]]
#name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "prettier"
