version: "3.1"
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgress
      POSTGRES_USER: postgress
      POSTGRES_DB: postgres

  redis:
    image: redis
    command: --port 6666
    ports:
      - "6666:6666"
    expose:
      - "6666"
  leadminer_backend:
    build: ./backend
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    depends_on:
      - postgres
      - redis
  leadminer_frontend:
    build: ./frontend
    ports:
      - "80:80"
