version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: "./backend"
    environment:
      DATABASE_URL:
    ports:
      - 8081:8081
    volumes:
      - /app/node_modules
      - ./backend:/app
    links:
      - postgres
    networks:
      - backend
      - frontend
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14.1-alpine
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - 8082:80
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - frontend

networks:
  backend:
  frontend:
  intranet:
