version: "3.1"

services:
  redis:
    image: redis:alpine
    command: --port ${REDIS_PORT}
    restart: always

  leadminer-api:
    image: leadminer-api:git
    container_name: leadminer_api
    build:
      context: backend
      dockerfile: api.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - ${LEADMINER_API_PORT}:${LEADMINER_API_PORT}

  leadminer-worker:
    image: leadminer-worker:git
    container_name: leadminer_worker
    build:
      context: backend
      dockerfile: worker.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis

  leadminer-server:
    image: leadminer-server:git
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    build:
      context: frontend
      args:
        SERVER_ENDPOINT: ${LEADMINER_API_HOST}
        SUPABASE_PROJECT_URL: ${SUPABASE_PROJECT_URL}
        SUPABASE_SECRET_PROJECT_TOKEN: ${SUPABASE_SECRET_PROJECT_TOKEN}
        GG_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        SUPABASE_MAX_ROWS: ${SUPABASE_MAX_ROWS}
        AVERAGE_EXTRACTION_RATE: ${AVERAGE_EXTRACTION_RATE}
        BANNER_IMAGE_URL: ${BANNER_IMAGE_URL}
    ports:
      - 8020:80
    restart: always
    depends_on:
      - leadminer-api
