services:
  redis:
    image: redis:alpine
    command: --port ${REDIS_PORT}
    restart: always

  leadminer-api:
    image: leadminer-api:git
    container_name: leadminer_api
    build:
      context: backend
      dockerfile: api.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - ${LEADMINER_API_PORT}:${LEADMINER_API_PORT}

  leadminer-worker:
    image: leadminer-worker:git
    container_name: leadminer_worker
    build:
      context: backend
      dockerfile: worker.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis

  leadminer-email-worker:
    image: leadminer-email-worker:git
    container_name: leadminer_email_worker
    build:
      context: backend
      dockerfile: email-verification-worker.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis

  leadminer-signature-worker:
    image: leadminer-signature-worker:git
    container_name: leadminer_signature_worker
    build:
      context: backend
      dockerfile: email-signature-worker.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis

  leadminer-frontend:
    image: leadminer-frontend:git
    container_name: nuxt_frontend
    build:
      context: frontend
    environment:
      SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      SUPABASE_PROJECT_URL=${SUPABASE_EXTERNAL_PROJECT_URL}
      SAAS_SUPABASE_ANON_KEY=${SAAS_SUPABASE_ANON_KEY}
      SAAS_SUPABASE_PROJECT_URL=${SAAS_SUPABASE_PROJECT_URL}
      SERVER_ENDPOINT=${LEADMINER_API_HOST}
      AVERAGE_EXTRACTION_RATE=${AVERAGE_EXTRACTION_RATE}
      POSTHOG_API_KEY=${POSTHOG_API_KEY}
      POSTHOG_INSTANCE_ADDRESS=${POSTHOG_INSTANCE_ADDRESS}
      POSTHOG_STATIC_ASSETS_PROXY=${POSTHOG_STATIC_ASSETS_PROXY}
      POSTHOG_PROXY_ADDRESS=${POSTHOG_PROXY_ADDRESS}
      POSTHOG_INGEST_INSTANCE=${POSTHOG_INGEST_INSTANCE}
      ENABLE_CREDIT=${ENABLE_CREDIT}
      EXTERNAL_REFILL_CREDITS_LINK=${EXTERNAL_REFILL_CREDITS_LINK}
      CREDITS_PER_CONTACT=${CREDITS_PER_CONTACT}
      SENTRY_ENVIRONMENT_FRONTEND=${SENTRY_ENVIRONMENT_FRONTEND}
      SENTRY_DSN_FRONTEND=${SENTRY_DSN_FRONTEND}
      IMAGE_REVERSE_PROXY=${IMAGE_REVERSE_PROXY}
    ports:
      - 8082:3000
    restart: always
    depends_on:
      - leadminer-api
