version: "3.1"
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}

  redis:
    image: redis
    command: --port ${REDIS_PORT:-6379}
    restart: always
  leadminer-api:
    image: leadminer-api:git
    container_name: leadminer_api
    build: backend
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
      - redis
    ports:
      - 8081:8081
  leadminer-server:
    image: leadminer-server:git
    container_name: nginx_server
    build: frontend
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - leadminer-api
