version: "3.1"
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgress
      POSTGRES_USER: postgress
      POSTGRES_DB: postgres

  redis:
    image: redis
    command: --port 6666
    ports:
      - "6666:6666"
    expose:
      - "6379"
  leadminerd:
    image: leadea01111:latest
    stdin_open: true
    tty: true
    ports:
      - "8060:8081"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgress
      POSTGRES_USER: postgress
      POSTGRES_DB: postgres
    depends_on:
      - postgres
      - redis
