import { ZerobounceEmailValidationResult } from '../../../../src/services/email-status/zerobounce/client';

// Mocked responses based on Zerobounce sandbox
// https://www.zerobounce.net/docs/email-validation-api-quickstart/#sandbox_mode__v2__

const sandbox: Record<string, ZerobounceEmailValidationResult> = {
  'invalid@example.com': {
    address: 'invalid@example.com',
    status: 'invalid',
    sub_status: 'mailbox_not_found',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.602'
  },
  'disposable@example.com': {
    address: 'disposable@example.com',
    status: 'do_not_mail',
    sub_status: 'disposable',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.628'
  },
  'valid@example.com': {
    address: 'valid@example.com',
    status: 'valid',
    sub_status: '',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:46:11.835'
  },
  'toxic@example.com': {
    address: 'toxic@example.com',
    status: 'do_not_mail',
    sub_status: 'toxic',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.647'
  },
  'spamtrap@example.com': {
    address: 'spamtrap@example.com',
    status: 'spamtrap',
    sub_status: '',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.726'
  },
  'donotmail@example.com': {
    address: 'donotmail@example.com',
    status: 'do_not_mail',
    sub_status: 'role_based',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.638'
  },
  'unknown@example.com': {
    address: 'unknown@example.com',
    status: 'unknown',
    sub_status: 'mail_server_temporary_error',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.605'
  },
  'abuse@example.com': {
    address: 'abuse@example.com',
    status: 'abuse',
    sub_status: '',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:46:10.687'
  },
  'antispam_system@example.com': {
    address: 'antispam_system@example.com',
    status: 'unknown',
    sub_status: 'antispam_system',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.621'
  },
  'exception_occurred@example.com': {
    address: 'exception_occurred@example.com',
    status: 'unknown',
    sub_status: 'exception_occurred',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.614'
  },
  'catch_all@example.com': {
    address: 'catch_all@example.com',
    status: 'catch-all',
    sub_status: '',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:46:11.533'
  },
  'failed_smtp_connection@example.com': {
    address: 'failed_smtp_connection@example.com',
    status: 'unknown',
    sub_status: 'failed_smtp_connection',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.619'
  },
  'failed_syntax_check@example.com': {
    address: 'failed_syntax_check@example.com',
    status: 'invalid',
    sub_status: 'failed_syntax_check',
    free_email: false,
    did_you_mean: null,
    account: '',
    domain: '',
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.621'
  },
  'does_not_accept_mail@example.com': {
    address: 'does_not_accept_mail@example.com',
    status: 'invalid',
    sub_status: 'does_not_accept_mail',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:46:08.076'
  },
  'forcible_disconnect@example.com': {
    address: 'forcible_disconnect@example.com',
    status: 'unknown',
    sub_status: 'forcible_disconnect',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.644'
  },
  'greylisted@example.com': {
    address: 'greylisted@example.com',
    status: 'unknown',
    sub_status: 'greylisted',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:14:37.719'
  },
  'leading_period_removed@example.com': {
    address: 'leading_period_removed@example.com',
    status: 'valid',
    sub_status: 'leading_period_removed',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.621'
  },
  'mail_server_did_not_respond@example.com': {
    address: 'mail_server_did_not_respond@example.com',
    status: 'unknown',
    sub_status: 'mail_server_did_not_respond',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.586'
  },
  'mailbox_quota_exceeded@example.com': {
    address: 'mailbox_quota_exceeded@example.com',
    status: 'invalid',
    sub_status: 'mailbox_quota_exceeded',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.654'
  },
  'global_suppression@example.com': {
    address: 'global_suppression@example.com',
    status: 'do_not_mail',
    sub_status: 'global_suppression',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.610'
  },
  'mail_server_temporary_error@example.com': {
    address: 'mail_server_temporary_error@example.com',
    status: 'unknown',
    sub_status: 'mail_server_temporary_error',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:46:11.669'
  },
  'mailbox_not_found@example.com': {
    address: 'mailbox_not_found@example.com',
    status: 'invalid',
    sub_status: 'mailbox_not_found',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:46:38.200'
  },
  'no_dns_entries@example.com': {
    address: 'no_dns_entries@example.com',
    status: 'invalid',
    sub_status: 'no_dns_entries',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.641'
  },
  'possible_typo@example.com': {
    address: 'possible_typo@example.com',
    status: 'invalid',
    sub_status: 'possible_typo',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.660'
  },
  'role_based@example.com': {
    address: 'role_based@example.com',
    status: 'do_not_mail',
    sub_status: 'role_based',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.674'
  },
  'timeout_exceeded@example.com': {
    address: 'timeout_exceeded@example.com',
    status: 'unknown',
    sub_status: 'timeout_exceeded',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:16.328'
  },
  'unroutable_ip_address@example.com': {
    address: 'unroutable_ip_address@example.com',
    status: 'invalid',
    sub_status: 'unroutable_ip_address',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:16.291'
  },
  'possible_trap@example.com': {
    address: 'possible_trap@example.com',
    status: 'do_not_mail',
    sub_status: 'possible_trap',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:42:14.637'
  },
  'free_email@example.com': {
    address: 'free_email@example.com',
    status: 'valid',
    sub_status: '',
    free_email: true,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:25:35.549'
  },
  'role_based_catch_all@example.com': {
    address: 'role_based_catch_all@example.com',
    status: 'do_not_mail',
    sub_status: 'role_based_catch_all',
    free_email: false,
    did_you_mean: null,
    account: null,
    domain: null,
    domain_age_days: '9692',
    smtp_provider: 'example',
    mx_found: 'true',
    mx_record: 'mx.example.com',
    firstname: 'zero',
    lastname: 'bounce',
    gender: 'male',
    country: null,
    region: null,
    city: null,
    zipcode: null,
    processed_at: '2024-06-20 15:46:38.697'
  }
};

export default sandbox;
