name: Auto Merge Snyk Branches

on:
  push:
    branches:
      - 'snyk*'  # Trigger when changes are pushed to any snyk branch

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Get the PR associated with the snyk branch
      - name: Get PR from snyk/* branch
        id: pr
        run: |
          sleep 10 # delay the PR check to prevent checking before the PR is opened
          echo "Looking for PR related to ${{ github.ref_name }}"
          pr_number=$(gh pr list --state open --head ${{ github.ref_name }} --json number -q '.[0].number')
          if [ -z "$pr_number" ]; then
            echo "No PR found for ${{ github.ref_name }}."
            exit 0
          fi
          echo "Found PR number: $pr_number"
          echo "pr_number=$pr_number" >> "$GITHUB_ENV"

      # Merge the pull request
      - name: Auto Merge PR
        uses: pascalgn/automerge-action@v0.16.3
        with:
          merge_method: squash  # Options: merge, squash, rebase
          pull_request: $pr_number
          delete_branch: true
