name: Run CI checks
on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: cd backend && npm ci
      - name: Check linting
        run: cd backend && npm run lint
      - name: Check formatting
        run: cd backend && npm run prettier
      - name: Run unit tests
        run: cd backend && npm run test-ci:unit
      - uses: jgillick/test-coverage-reporter@main
        with:
          coverage-file: backend/coverage/coverage-summary.json
          access-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'pull_request' }}
      - name: Update DeepSource code coverage
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./backend/coverage/lcov.info
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Check linting
        run: cd frontend && npm run lint
      - name: Check formatting
        run: cd frontend && npm run prettier
      # - name: Run unit tests (One day)
      #   run: cd frontend && npm run test:unit
