name: Run CI checks
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: cd backend && npm ci
      - name: Check linting
        run: cd backend && npm run lint
      - name: Check formatting
        run: cd backend && npm run prettier
      - name: Run unit tests
        run: cd backend && npm run test-ci:unit

      - name: debug
        run: cd backend && ls -R

      - uses: jgillick/test-coverage-reporter@main
        with:
          coverage-file: backend/coverage/coverage-summary.json
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update DeepSource code coverage
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./backend/coverage/lcov.info
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Check linting
        run: cd frontend && npm run lint
      - name: Check formatting
        run: cd frontend && npm run prettier
      # - name: Run unit tests (One day)
      #   run: cd frontend && npm run test:unit
