name: Run CI checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  filter:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      actions: ${{ steps.filter.outputs.actions }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            actions: 
              - '.github/workflows/**'

  backend:
    needs: changes
    if: ${{ steps.filter.outputs.backend == 'true' || steps.filter.outputs.actions == 'true'  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: cd backend && npm ci
      - run: cd backend && npm run lint
      - run: cd backend && npm run prettier
      - run: cd backend && npm run test:unit
      - name: DeepSource code coverage report
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./backend/coverage/lcov.info
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
