name: Run CI checks
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Auto Merge Snyk Branches"]
    types:
      - completed

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: cd backend && npm ci
      - name: Run unit tests
        run: cd backend && npm run test-ci:unit
      - name: Report code coverage to Deepsource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./backend/coverage/lcov.info
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: backend/coverage/lcov-report/jacocoTestReport.csv
          badges-directory: backend/coverage/lcov-report/html/badges
      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: backend/coverage/lcov-report/html
      - name: Check linting
        run: cd backend && npm run lint
      - name: Check formatting
        run: cd backend && npm run prettier

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Check linting
        run: cd frontend && npm run lint
      - name: Check formatting
        run: cd frontend && npm run prettier
      # - name: Run unit tests (One day)
      #   run: cd frontend && npm run test:unit
