name: Deploy Leadminer Demo
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Leadminer
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server
          script: |
            TARGET=demo
            ( cd leadminer_$TARGET; docker-compose down; git pull)
            ( cd leadminer.io; . .env.$TARGET ; psql \
                -Atx "$PG_CONNECTION_STRING" \
                -c "TRUNCATE table messages, persons, pointsofcontact, refinedpersons, tags;"
              git pull
            )
            cp leadminer.io/.env.$TARGET leadminer_$TARGET/.env
            cp leadminer.io/docker-compose.yml leadminer_$TARGET
            cd leadminer_$TARGET

            docker images --format '{{.Repository}}:{{.Tag}}' | grep 'lead' | xargs -n 1 docker rmi
            docker ps -a -q | xargs -n 1 docker rm
            docker-compose up -d \
              --build \
              --force-recreate
