name: Build & Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Leadminer
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server
          script: |
            config_path="backend/config/production.yaml"
            cd leadminer
            git pull
            # Use POSTGRES_PASSWORD if defined, else get password from the config
            DB_PASSWORD="${POSTGRES_PASSWORD:-$(niet server.postgres.password "$config_path")}"
            export DB_PASSWORD # Database Password
            docker-compose down
            docker rmi -f $(docker images -a | awk '/leadminer|<none>/{print $3}')
            docker-compose up -d --build
