name: Leadminer-prod
on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Leadminer Prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{vars.SSH_HOST_LEADMINER}} # IP address of the server
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server
          script: |
            TARGET=prod
            ( cd leadminer_$TARGET; docker-compose down; git pull)
            ( cd leadminer.io; . .env.$TARGET; git pull; psql \
                -Atx "$PG_CONNECTION_STRING" \
                -c "TRUNCATE table messages, persons, pointsofcontact, refinedpersons, tags;"
            )
            cp leadminer.io/.env.$TARGET leadminer_$TARGET/.env
            cp leadminer.io/docker-compose.yml leadminer_$TARGET
            cd leadminer_$TARGET

            eval "docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'lead')"
            docker images --format '{{.Repository}}:{{.Tag}}' | grep 'lead' | xargs -n 1 docker rmi
            docker-compose -d up \
              --build \
              --force-recreate

            docker image prune -a -f     
