name: Run Integration Tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setting up NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "7.x"
      - run: redis-cli ping
      - name: Install dependencies
        run: cd backend && npm install
      - name: Copy config file
        run: cd backend && cp ./config/example.yml ./config/default.yml
      - name: Run tests
        run: cd backend && npm run test:integration
        env:
          TEST_IMAP_HOST: ${{ secrets.TEST_IMAP_HOST }}
          TEST_IMAP_PASSWORD: ${{ secrets.TEST_IMAP_PASSWORD }}
          TEST_IMAP_EMAIL: ${{ secrets.TEST_IMAP_EMAIL }}
