name: Push Supabase functions to leadminer.io
on:
  push:
    branches: [main]
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Clone destination repository
        run: |
          git clone https://${{ secrets.DEPLOY_PAT }}@github.com/ankaboot-source/leadminer.io.git leadminer.io

      - name: Delete existing files in destination repo
        run: |
          rm -rf leadminer.io/supabase/functions/*

      - name: Copy new files to destination repo
        run: |
          cp -r supabase/functions/. leadminer.io/supabase/functions/

      - name: Commit and push changes
        run: |
          cd leadminer.io
          git config user.name "deploy-leadminer"
          git config user.email "deploy@leadminer.io"
          git add -A
          git commit -m "Update Supabase functions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_PAT }}
