name: Trigger QA deployment [backend build]

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'


jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Leadminer.io repository
        run: |
          repo_owner="ankaboot-source"
          repo_name="leadminer.io"
          event_type="trigger-qa-backend-build"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\"}"
