name: Self hosted Supabase migrations
on:
  push:
    branches: [deploy]
  #workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

    steps:

      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.42.0

      - run: |
          supabase db init --db-url $SUPABASE_DB_URL
          cd ./supabase/migrations
          supabase db push --db-url $SUPABASE_DB_URL --debug
