name: Self hosted Supabase migrations
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      firewall_id: ${{ steps.firewall_id.outputs.output }}
      droplet_id: ${{ steps.droplet_id.outputs.output }}
      inbound_rules: ${{ steps.inbound_rules.outputs.output }}
      outbound_rules: ${{ steps.inbound_rules.outputs.output }}
    steps:
      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - id: firewall_id
        run: echo "output='$(doctl compute firewall list --no-header --format Name,ID | awk '/supabase-firewall/{print $2}')'" >> "$GITHUB_OUTPUT"
      - id: droplet_id
        run: echo "output='$(doctl compute firewall list --no-header --format Name,DropletIDs | awk '/supabase-firewall/{print $2}')'" >> "$GITHUB_OUTPUT"
      - id: inbound_rules
        run: echo "output='$(
            doctl compute firewall list --no-header --format Name,InboundRules |
              awk '/supabase-firewall/{
                for (i=2; i<=NF; i++)
                  printf "%s ", $i
                printf $NF
              }'
          )'" >> "$GITHUB_OUTPUT"
      - id: outbound_rules
        run: echo "output='$(
            doctl compute firewall list --no-header --format Name,OutboundRules |
              awk '/supabase-firewall/{
                for (i=2; i<=NF-1; i++)
                  printf "%s ", $i
                print $NF
              }'
          )'" >> "$GITHUB_OUTPUT"

  release:
    runs-on: ubuntu-latest
    needs: prepare
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      FIREWALL_ID: ${{needs.prepare.outputs.firewall_id}}
      DROPLET_ID: ${{needs.prepare.outputs.droplet_id}}
      INBOUND_RULES: ${{needs.prepare.outputs.inbound_rules}}
      OUTBOUND_RULES: ${{needs.prepare.outputs.outbound_rules}}
    steps:
      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Allow through firewall
        run: |
          RUNNER_IP="$(hostname -I | awk '{print $1}')"
          NEW_INBOUND="$(echo $INBOUND_RULES | sed "s/5432/5432,address:${RUNNER_IP}/g")"
          doctl compute firewall update $FIREWALL_ID --name supabase-firewall --inbound-rules $NEW_INBOUND --outbound-rules $OUTBOUND_RULES --droplet-ids $DROPLET_ID

      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.50.13
      - name: Push Supabase DB Migrations
        run: |
          supabase db push --db-url $SUPABASE_DB_URL --debug
          doctl compute firewall update $FIREWALL_ID --name supabase-firewall --inbound-rules $INBOUND_RULES --outbound-rules $OUTBOUND_RULES --droplet-ids $DROPLET_ID
