name: Self hosted Supabase migrations
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - name: Setup DigitalOcean firewall
        uses: earthpyy/setup-digitalocean-firewall@v1
        with:
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          firewall-id: 62c6f1cf-7a0a-4517-8985-4e84b92ced1a
          ports: '5432/tcp'

      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.50.13
      - name: Push Supabase DB Migrations
        run: |
          supabase db push --db-url $SUPABASE_DB_URL --debug
