name: Run Unit Tests
on: [pull_request]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: cd backend && npm install
      - name: Run tests
        run: cd backend && npm run test:unit 
      - name: DeepSource Code Coverage Report
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: ./coverage/lcov.info
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
 
