name: Run Unit Tests
on: [pull_request]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setting up NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run tests
        run: cd backend && npm run test:unit 

      - name: install lcov-total
        run: cd backend && npm install -g lcov-total

      - name: parse lcov total
        run: echo $(npx lcov-total ./backend/coverage/lcov.info) >> lcov.txt

      - name: persist coverage file
        uses: actions/upload-artifact@v3
        with:
          name: Coverage-artifact
          path: ./lcov.txt

      - name: DeepSource code coverage report 
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./backend/coverage/lcov.info
        env:    
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
 
